# Generated by Django 5.2.4 on 2025-08-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='department_id',
            new_name='department',
        ),
    ]
