# Generated by Django 5.2.4 on 2025-08-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_role_id_employee_role_and_more'),
    ]

    operations = [
    ]
