# Generated by Django 5.2.4 on 2025-10-20 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_seniority', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], help_text='Seniority level before the change', max_length=10)),
                ('new_seniority', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], help_text='Seniority level after the change', max_length=10)),
                ('change_reason', models.CharField(blank=True, help_text="Reason for the role change(e.g. 'Promotion', 'Internal transfer'.)", max_length=255)),
                ('effective_date', models.DateField(help_text='Date when the new role takes effect')),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to='employee.employee')),
                ('new_role', models.ForeignKey(help_text='Role after the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_as_new_role', to='employee.role')),
                ('old_role', models.ForeignKey(help_text='Role before the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_as_old_role', to='employee.role')),
            ],
            options={
                'verbose_name_plural': 'Role histories',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', '-effective_date'], name='employee_ro_employe_b0bf3c_idx'), models.Index(fields=['changed_by', '-created_at'], name='employee_ro_changed_21811f_idx'), models.Index(fields=['old_role'], name='employee_ro_old_rol_f189e5_idx'), models.Index(fields=['new_role'], name='employee_ro_new_rol_84393e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_salary', models.DecimalField(decimal_places=2, help_text='Salary before the change', max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, help_text='Salary after the change', max_digits=10)),
                ('change_reason', models.CharField(blank=True, help_text="Reason for the salary change (e.g 'Annual raise', 'Promotion')", max_length=255)),
                ('effective_date', models.DateField(help_text='Date when the new salary takes effect')),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Salaries histories',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', '-effective_date'], name='employee_sa_employe_9f7f5a_idx'), models.Index(fields=['changed_by', '-created_at'], name='employee_sa_changed_56b0d8_idx')],
            },
        ),
    ]
